In [1]:
import pandas as pd
import numpy as np
import os
import regex as re

In [2]:
df = pd.read_html('annual_sales_by_model/fiat_jeep_citroen.html')[1]
df

,Group,Maker/Brand,Segment,Model,PowerTrain,Country,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Stellantis,Jeep (2021-),SUV-C,Compass (Jeep (2009-)),NaN,India,-,-,-,-,-,-,-,-,-,11652,9866,4054
1,Stellantis,Jeep (2021-),SUV-C,Compass (Jeep (2009-)),Compass (Jeep (2009-)) Total,Compass (Jeep (2009-)) Total,-,-,-,-,-,-,-,-,-,11652,9866,4054
2,Stellantis,Jeep (2021-),SUV-C,SUV-C Total,SUV-C Total,SUV-C Total,-,-,-,-,-,-,-,-,-,11652,9866,4054
3,Stellantis,Jeep (2021-),SUV-D,Meridian,NaN,India,-,-,-,-,-,-,-,-,-,-,3451,2571
4,Stellantis,Jeep (2021-),SUV-D,Meridian,Meridian Total,Meridian Total,-,-,-,-,-,-,-,-,-,-,3451,2571
5,Stellantis,Jeep (2021-),SUV-D,SUV-D Total,SUV-D Total,SUV-D Total,-,-,-,-,-,-,-,-,-,-,3451,2571
6,Stellantis,Jeep (2021-),Jeep (2021-) Total,Jeep (2021-) Total,Jeep (2021-) Total,Jeep (2021-) Total,-,-,-,-,-,-,-,-,-,11652,13317,6625
7,Stellantis,Citroen (2021-),B,C3,EV,India,-,-,-,-,-,-,-,-,-,-,-,2360
8,Stellantis,Citroen (2021-),B,C3,NaN,India,-,-,-,-,-,-,-,-,-,-,5686,5738
9,Stellantis,Citroen (2021-),B,C3,C3 Total,C3 Total,-,-,-,-,-,-,-,-,-,-,5686,8098
10,Stellantis,Citroen (2021-),B,B Total,B Total,B Total,-,-,-,-,-,-,-,-,-,-,5686,8098
11,Stellantis,Citroen (2021-),SUV-B,C3 Aircross,NaN,India,-,-,-,-,-,-,-,-,-,-,-,1212
12,Stellantis,Citroen (2021-),SUV-B,C3 Aircross,C3 Aircross Total,C3 Aircross Total,-,-,-,-,-,-,-,-,-,-,-,1212
13,Stellantis,Citroen (2021-),SUV-B,SUV-B Total,SUV-B Total,SUV-B Total,-,-,-,-,-,-,-,-,-,-,-,1212
14,Stellantis,Citroen (2021-),SUV-C,C5 Aircross,NaN,India,-,-,-,-,-,-,-,-,-,624,380,127
15,Stellantis,Citroen (2021-),SUV-C,C5 Aircross,C5 Aircross Total,C5 Aircross Total,-,-,-,-,-,-,-,-,-,624,380,127
16,Stellantis,Citroen (2021-),SUV-C,SUV-C Total,SUV-C Total,SUV-C Total,-,-,-,-,-,-,-,-,-,624,380,127
17,Stellantis,Citroen (2021-),Citroen (2021-) Total,Citroen (2021-) Total,Citroen (2021-) Total,Citroen (2021-) Total,-,-,-,-,-,-,-,-,-,624,6066,9437
18,Stellantis,Stellantis Total,Stellantis Total,Stellantis Total,Stellantis Total,Stellantis Total,-,-,-,-,-,-,-,-,-,12276,19383,16062
19,FCA,Fiat (-2020),B,Grande Punto,NaN,India,-,-,8442,4694,4334,1372,372,103,-,-,-,-
20,FCA,Fiat (-2020),B,Grande Punto,Grande Punto Total,Grande Punto Total,-,-,8442,4694,4334,1372,372,103,-,-,-,-
21,FCA,Fiat (-2020),B,B Total,B Total,B Total,-,-,8442,4694,4334,1372,372,103,-,-,-,-
22,FCA,Fiat (-2020),C,Linea,NaN,India,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
23,FCA,Fiat (-2020),C,Linea,Linea Total,Linea Total,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
24,FCA,Fiat (-2020),C,C Total,C Total,C Total,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
25,FCA,Fiat (-2020),SUV-B,Avventura,NaN,India,-,-,909,2170,1230,831,256,99,-,-,-,-
26,FCA,Fiat (-2020),SUV-B,Avventura,Avventura Total,Avventura Total,-,-,909,2170,1230,831,256,99,-,-,-,-
27,FCA,Fiat (-2020),SUV-B,SUV-B Total,SUV-B Total,SUV-B Total,-,-,909,2170,1230,831,256,99,-,-,-,-
28,FCA,Fiat (-2020),Fiat (-2020) Total,Fiat (-2020) Total,Fiat (-2020) Total,Fiat (-2020) Total,2593,2370,12366,8566,6655,2690,743,302,-,-,-,-
29,FCA,Jeep (2009-20),SUV-C,Compass (Jeep (2009-)),NaN,India,-,-,-,-,-,13139,18286,10935,5209,-,-,-
30,FCA,Jeep (2009-20),SUV-C,Compass (Jeep (2009-)),Compass (Jeep (2009-)) Total,Compass (Jeep (2009-)) Total,-,-,-,-,-,13139,18286,10935,5209,-,-,-
31,FCA,Jeep (2009-20),SUV-C,SUV-C Total,SUV-C Total,SUV-C Total,-,-,-,-,-,13139,18286,10935,5209,-,-,-
32,FCA,Jeep (2009-20),Jeep (2009-20) Total,Jeep (2009-20) Total,Jeep (2009-20) Total,Jeep (2009-20) Total,-,-,-,-,-,13139,18286,10935,5209,-,-,-
33,FCA,FCA Total,FCA Total,FCA Total,FCA Total,FCA Total,2593,2370,12366,8566,6655,15829,19029,11237,5209,-,-,-
34,Grand Total,Grand Total,Grand Total,Grand Total,Grand Total,Grand Total,2593,2370,12366,8566,6655,15829,19029,11237,5209,12276,19383,16062

In [3]:
df.drop(columns=['Group','Country'],inplace=True)
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep (2021-),SUV-C,Compass (Jeep (2009-)),NaN,-,-,-,-,-,-,-,-,-,11652,9866,4054
1,Jeep (2021-),SUV-C,Compass (Jeep (2009-)),Compass (Jeep (2009-)) Total,-,-,-,-,-,-,-,-,-,11652,9866,4054
2,Jeep (2021-),SUV-C,SUV-C Total,SUV-C Total,-,-,-,-,-,-,-,-,-,11652,9866,4054
3,Jeep (2021-),SUV-D,Meridian,NaN,-,-,-,-,-,-,-,-,-,-,3451,2571
4,Jeep (2021-),SUV-D,Meridian,Meridian Total,-,-,-,-,-,-,-,-,-,-,3451,2571
5,Jeep (2021-),SUV-D,SUV-D Total,SUV-D Total,-,-,-,-,-,-,-,-,-,-,3451,2571
6,Jeep (2021-),Jeep (2021-) Total,Jeep (2021-) Total,Jeep (2021-) Total,-,-,-,-,-,-,-,-,-,11652,13317,6625
7,Citroen (2021-),B,C3,EV,-,-,-,-,-,-,-,-,-,-,-,2360
8,Citroen (2021-),B,C3,NaN,-,-,-,-,-,-,-,-,-,-,5686,5738
9,Citroen (2021-),B,C3,C3 Total,-,-,-,-,-,-,-,-,-,-,5686,8098
10,Citroen (2021-),B,B Total,B Total,-,-,-,-,-,-,-,-,-,-,5686,8098
11,Citroen (2021-),SUV-B,C3 Aircross,NaN,-,-,-,-,-,-,-,-,-,-,-,1212
12,Citroen (2021-),SUV-B,C3 Aircross,C3 Aircross Total,-,-,-,-,-,-,-,-,-,-,-,1212
13,Citroen (2021-),SUV-B,SUV-B Total,SUV-B Total,-,-,-,-,-,-,-,-,-,-,-,1212
14,Citroen (2021-),SUV-C,C5 Aircross,NaN,-,-,-,-,-,-,-,-,-,624,380,127
15,Citroen (2021-),SUV-C,C5 Aircross,C5 Aircross Total,-,-,-,-,-,-,-,-,-,624,380,127
16,Citroen (2021-),SUV-C,SUV-C Total,SUV-C Total,-,-,-,-,-,-,-,-,-,624,380,127
17,Citroen (2021-),Citroen (2021-) Total,Citroen (2021-) Total,Citroen (2021-) Total,-,-,-,-,-,-,-,-,-,624,6066,9437
18,Stellantis Total,Stellantis Total,Stellantis Total,Stellantis Total,-,-,-,-,-,-,-,-,-,12276,19383,16062
19,Fiat (-2020),B,Grande Punto,NaN,-,-,8442,4694,4334,1372,372,103,-,-,-,-
20,Fiat (-2020),B,Grande Punto,Grande Punto Total,-,-,8442,4694,4334,1372,372,103,-,-,-,-
21,Fiat (-2020),B,B Total,B Total,-,-,8442,4694,4334,1372,372,103,-,-,-,-
22,Fiat (-2020),C,Linea,NaN,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
23,Fiat (-2020),C,Linea,Linea Total,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
24,Fiat (-2020),C,C Total,C Total,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
25,Fiat (-2020),SUV-B,Avventura,NaN,-,-,909,2170,1230,831,256,99,-,-,-,-
26,Fiat (-2020),SUV-B,Avventura,Avventura Total,-,-,909,2170,1230,831,256,99,-,-,-,-
27,Fiat (-2020),SUV-B,SUV-B Total,SUV-B Total,-,-,909,2170,1230,831,256,99,-,-,-,-
28,Fiat (-2020),Fiat (-2020) Total,Fiat (-2020) Total,Fiat (-2020) Total,2593,2370,12366,8566,6655,2690,743,302,-,-,-,-
29,Jeep (2009-20),SUV-C,Compass (Jeep (2009-)),NaN,-,-,-,-,-,13139,18286,10935,5209,-,-,-
30,Jeep (2009-20),SUV-C,Compass (Jeep (2009-)),Compass (Jeep (2009-)) Total,-,-,-,-,-,13139,18286,10935,5209,-,-,-
31,Jeep (2009-20),SUV-C,SUV-C Total,SUV-C Total,-,-,-,-,-,13139,18286,10935,5209,-,-,-
32,Jeep (2009-20),Jeep (2009-20) Total,Jeep (2009-20) Total,Jeep (2009-20) Total,-,-,-,-,-,13139,18286,10935,5209,-,-,-
33,FCA Total,FCA Total,FCA Total,FCA Total,2593,2370,12366,8566,6655,15829,19029,11237,5209,-,-,-
34,Grand Total,Grand Total,Grand Total,Grand Total,2593,2370,12366,8566,6655,15829,19029,11237,5209,12276,19383,16062

In [4]:
df['PowerTrain'].fillna('ICE',inplace=True)

In [5]:
df.drop(index=df[df['PowerTrain'].str.contains('Total')].index,inplace=True)

In [6]:
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep (2021-),SUV-C,Compass (Jeep (2009-)),ICE,-,-,-,-,-,-,-,-,-,11652,9866,4054
3,Jeep (2021-),SUV-D,Meridian,ICE,-,-,-,-,-,-,-,-,-,-,3451,2571
7,Citroen (2021-),B,C3,EV,-,-,-,-,-,-,-,-,-,-,-,2360
8,Citroen (2021-),B,C3,ICE,-,-,-,-,-,-,-,-,-,-,5686,5738
11,Citroen (2021-),SUV-B,C3 Aircross,ICE,-,-,-,-,-,-,-,-,-,-,-,1212
14,Citroen (2021-),SUV-C,C5 Aircross,ICE,-,-,-,-,-,-,-,-,-,624,380,127
19,Fiat (-2020),B,Grande Punto,ICE,-,-,8442,4694,4334,1372,372,103,-,-,-,-
22,Fiat (-2020),C,Linea,ICE,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
25,Fiat (-2020),SUV-B,Avventura,ICE,-,-,909,2170,1230,831,256,99,-,-,-,-
29,Jeep (2009-20),SUV-C,Compass (Jeep (2009-)),ICE,-,-,-,-,-,13139,18286,10935,5209,-,-,-

In [7]:
df[df['Maker/Brand'].str.contains(r'\W\d{0,}-\d{0,4}\W')]['Maker/Brand']

0        Jeep (2021-)
3        Jeep (2021-)
7     Citroen (2021-)
8     Citroen (2021-)
11    Citroen (2021-)
14    Citroen (2021-)
19       Fiat (-2020)
22       Fiat (-2020)
25       Fiat (-2020)
29     Jeep (2009-20)
Name: Maker/Brand, dtype: object

In [8]:
for value in df[df['Maker/Brand'].str.contains(r'\W\d{0,}-\d{0,4}\W')][['Maker/Brand']].iterrows():
    df.loc[value[0],'Maker/Brand'] = value[1].values[0].split()[0]
    
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV-C,Compass (Jeep (2009-)),ICE,-,-,-,-,-,-,-,-,-,11652,9866,4054
3,Jeep,SUV-D,Meridian,ICE,-,-,-,-,-,-,-,-,-,-,3451,2571
7,Citroen,B,C3,EV,-,-,-,-,-,-,-,-,-,-,-,2360
8,Citroen,B,C3,ICE,-,-,-,-,-,-,-,-,-,-,5686,5738
11,Citroen,SUV-B,C3 Aircross,ICE,-,-,-,-,-,-,-,-,-,-,-,1212
14,Citroen,SUV-C,C5 Aircross,ICE,-,-,-,-,-,-,-,-,-,624,380,127
19,Fiat,B,Grande Punto,ICE,-,-,8442,4694,4334,1372,372,103,-,-,-,-
22,Fiat,C,Linea,ICE,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
25,Fiat,SUV-B,Avventura,ICE,-,-,909,2170,1230,831,256,99,-,-,-,-
29,Jeep,SUV-C,Compass (Jeep (2009-)),ICE,-,-,-,-,-,13139,18286,10935,5209,-,-,-

In [9]:
df[df['Model'].str.contains(r'\W\D{0,}\W\d{0,}-\d{0,4}\W\W')]['Model']

0     Compass (Jeep (2009-))
29    Compass (Jeep (2009-))
Name: Model, dtype: object

In [10]:
import pdb

In [11]:
for value in df[df['Model'].str.contains(r'\W\D{0,}\W\d{0,}-\d{0,4}\W\W')][['Model']].iterrows():
    df.loc[value[0],'Model'] = value[1].values[0].split()[0]
    
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV-C,Compass,ICE,-,-,-,-,-,-,-,-,-,11652,9866,4054
3,Jeep,SUV-D,Meridian,ICE,-,-,-,-,-,-,-,-,-,-,3451,2571
7,Citroen,B,C3,EV,-,-,-,-,-,-,-,-,-,-,-,2360
8,Citroen,B,C3,ICE,-,-,-,-,-,-,-,-,-,-,5686,5738
11,Citroen,SUV-B,C3 Aircross,ICE,-,-,-,-,-,-,-,-,-,-,-,1212
14,Citroen,SUV-C,C5 Aircross,ICE,-,-,-,-,-,-,-,-,-,624,380,127
19,Fiat,B,Grande Punto,ICE,-,-,8442,4694,4334,1372,372,103,-,-,-,-
22,Fiat,C,Linea,ICE,2593,2370,3015,1702,1091,487,115,100,-,-,-,-
25,Fiat,SUV-B,Avventura,ICE,-,-,909,2170,1230,831,256,99,-,-,-,-
29,Jeep,SUV-C,Compass,ICE,-,-,-,-,-,13139,18286,10935,5209,-,-,-

In [12]:
df.replace('-',np.nan,inplace=True)
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV-C,Compass,ICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11652,9866,4054
3,Jeep,SUV-D,Meridian,ICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3451,2571
7,Citroen,B,C3,EV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2360
8,Citroen,B,C3,ICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5686,5738
11,Citroen,SUV-B,C3 Aircross,ICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1212
14,Citroen,SUV-C,C5 Aircross,ICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,624,380,127
19,Fiat,B,Grande Punto,ICE,NaN,NaN,8442,4694,4334,1372,372,103,NaN,NaN,NaN,NaN
22,Fiat,C,Linea,ICE,2593,2370,3015,1702,1091,487,115,100,NaN,NaN,NaN,NaN
25,Fiat,SUV-B,Avventura,ICE,NaN,NaN,909,2170,1230,831,256,99,NaN,NaN,NaN,NaN
29,Jeep,SUV-C,Compass,ICE,NaN,NaN,NaN,NaN,NaN,13139,18286,10935,5209,NaN,NaN,NaN

In [13]:
df.dropna(thresh=4,inplace=True)

In [14]:
df.replace(np.nan,0,inplace=True)

In [15]:
df.columns

Index(['Maker/Brand', 'Segment', 'Model', 'PowerTrain', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'],
      dtype='object')

In [16]:
years = df.columns[4:]
years

Index(['2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023'],
      dtype='object')

In [17]:
df.dtypes

Maker/Brand    object
Segment        object
Model          object
PowerTrain     object
2012           object
2013           object
2014           object
2015           object
2016           object
2017           object
2018           object
2019           object
2020           object
2021           object
2022           object
2023           object
dtype: object

In [18]:
df[years] = df[years].astype('float')

In [19]:
df.dtypes

Maker/Brand     object
Segment         object
Model           object
PowerTrain      object
2012           float64
2013           float64
2014           float64
2015           float64
2016           float64
2017           float64
2018           float64
2019           float64
2020           float64
2021           float64
2022           float64
2023           float64
dtype: object

In [20]:
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV-C,Compass,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11652.0,9866.0,4054.0
3,Jeep,SUV-D,Meridian,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3451.0,2571.0
7,Citroen,B,C3,EV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2360.0
8,Citroen,B,C3,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5686.0,5738.0
11,Citroen,SUV-B,C3 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1212.0
14,Citroen,SUV-C,C5 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.0,380.0,127.0
19,Fiat,B,Grande Punto,ICE,0.0,0.0,8442.0,4694.0,4334.0,1372.0,372.0,103.0,0.0,0.0,0.0,0.0
22,Fiat,C,Linea,ICE,2593.0,2370.0,3015.0,1702.0,1091.0,487.0,115.0,100.0,0.0,0.0,0.0,0.0
25,Fiat,SUV-B,Avventura,ICE,0.0,0.0,909.0,2170.0,1230.0,831.0,256.0,99.0,0.0,0.0,0.0,0.0
29,Jeep,SUV-C,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,0.0,0.0,0.0

In [21]:
for items in df.iterrows():
    print(items[1].values[:3])

['Jeep' 'SUV-C' 'Compass']
['Jeep' 'SUV-D' 'Meridian']
['Citroen' 'B' 'C3']
['Citroen' 'B' 'C3']
['Citroen' 'SUV-B' 'C3 Aircross']
['Citroen' 'SUV-C' 'C5 Aircross']
['Fiat' 'B' 'Grande Punto']
['Fiat' 'C' 'Linea']
['Fiat' 'SUV-B' 'Avventura']
['Jeep' 'SUV-C' 'Compass']

In [22]:
df[df[['Maker/Brand', 'Segment', 'Model', 'PowerTrain']].duplicated()]

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
29,Jeep,SUV-C,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,0.0,0.0,0.0

In [23]:
print(df[df[['Maker/Brand', 'Segment', 'Model', 'PowerTrain']].duplicated()].values[0][:3])

['Jeep' 'SUV-C' 'Compass']

In [24]:
for items in df.iterrows():
    if(list(items[1].values[:3])==list(df[df[['Maker/Brand', 'Segment', 'Model', 'PowerTrain']].duplicated()].values[0][:3])):
        df.loc[items[0],years]+=df[df[['Maker/Brand', 'Segment', 'Model', 'PowerTrain']].duplicated()][years].values[0]
        break
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV-C,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,11652.0,9866.0,4054.0
3,Jeep,SUV-D,Meridian,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3451.0,2571.0
7,Citroen,B,C3,EV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2360.0
8,Citroen,B,C3,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5686.0,5738.0
11,Citroen,SUV-B,C3 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1212.0
14,Citroen,SUV-C,C5 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.0,380.0,127.0
19,Fiat,B,Grande Punto,ICE,0.0,0.0,8442.0,4694.0,4334.0,1372.0,372.0,103.0,0.0,0.0,0.0,0.0
22,Fiat,C,Linea,ICE,2593.0,2370.0,3015.0,1702.0,1091.0,487.0,115.0,100.0,0.0,0.0,0.0,0.0
25,Fiat,SUV-B,Avventura,ICE,0.0,0.0,909.0,2170.0,1230.0,831.0,256.0,99.0,0.0,0.0,0.0,0.0
29,Jeep,SUV-C,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,0.0,0.0,0.0

In [25]:
df.drop(index=df[df[['Maker/Brand', 'Segment', 'Model', 'PowerTrain']].duplicated()].index,inplace=True)

In [26]:
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV-C,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,11652.0,9866.0,4054.0
3,Jeep,SUV-D,Meridian,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3451.0,2571.0
7,Citroen,B,C3,EV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2360.0
8,Citroen,B,C3,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5686.0,5738.0
11,Citroen,SUV-B,C3 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1212.0
14,Citroen,SUV-C,C5 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.0,380.0,127.0
19,Fiat,B,Grande Punto,ICE,0.0,0.0,8442.0,4694.0,4334.0,1372.0,372.0,103.0,0.0,0.0,0.0,0.0
22,Fiat,C,Linea,ICE,2593.0,2370.0,3015.0,1702.0,1091.0,487.0,115.0,100.0,0.0,0.0,0.0,0.0
25,Fiat,SUV-B,Avventura,ICE,0.0,0.0,909.0,2170.0,1230.0,831.0,256.0,99.0,0.0,0.0,0.0,0.0

In [27]:
for indx,value in zip(range(0,len(df)),df['Segment'].values):
    if re.search('SUV',value) or value=='MPV':
        df.iloc[indx,1] = 'SUV'
        continue
    elif value in ['A','B','C','D','E','F']:
        df.iloc[indx,1] = 'PassengerCar'
        continue
    elif value == 'Pickup Truck':
        df.iloc[indx,1] = 'LightTruck'
        continue
        
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,11652.0,9866.0,4054.0
3,Jeep,SUV,Meridian,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3451.0,2571.0
7,Citroen,PassengerCar,C3,EV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2360.0
8,Citroen,PassengerCar,C3,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5686.0,5738.0
11,Citroen,SUV,C3 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1212.0
14,Citroen,SUV,C5 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.0,380.0,127.0
19,Fiat,PassengerCar,Grande Punto,ICE,0.0,0.0,8442.0,4694.0,4334.0,1372.0,372.0,103.0,0.0,0.0,0.0,0.0
22,Fiat,PassengerCar,Linea,ICE,2593.0,2370.0,3015.0,1702.0,1091.0,487.0,115.0,100.0,0.0,0.0,0.0,0.0
25,Fiat,SUV,Avventura,ICE,0.0,0.0,909.0,2170.0,1230.0,831.0,256.0,99.0,0.0,0.0,0.0,0.0

In [28]:
df.drop(index=df[df['Segment']=='Unclassified'].index,axis=0,inplace=True)
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Jeep,SUV,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,11652.0,9866.0,4054.0
3,Jeep,SUV,Meridian,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3451.0,2571.0
7,Citroen,PassengerCar,C3,EV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2360.0
8,Citroen,PassengerCar,C3,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5686.0,5738.0
11,Citroen,SUV,C3 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1212.0
14,Citroen,SUV,C5 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.0,380.0,127.0
19,Fiat,PassengerCar,Grande Punto,ICE,0.0,0.0,8442.0,4694.0,4334.0,1372.0,372.0,103.0,0.0,0.0,0.0,0.0
22,Fiat,PassengerCar,Linea,ICE,2593.0,2370.0,3015.0,1702.0,1091.0,487.0,115.0,100.0,0.0,0.0,0.0,0.0
25,Fiat,SUV,Avventura,ICE,0.0,0.0,909.0,2170.0,1230.0,831.0,256.0,99.0,0.0,0.0,0.0,0.0

In [29]:
df['Total'] = df[years].sum(axis=1)
df

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Total
0,Jeep,SUV,Compass,ICE,0.0,0.0,0.0,0.0,0.0,13139.0,18286.0,10935.0,5209.0,11652.0,9866.0,4054.0,73141.0
3,Jeep,SUV,Meridian,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3451.0,2571.0,6022.0
7,Citroen,PassengerCar,C3,EV,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2360.0,2360.0
8,Citroen,PassengerCar,C3,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5686.0,5738.0,11424.0
11,Citroen,SUV,C3 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1212.0,1212.0
14,Citroen,SUV,C5 Aircross,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,624.0,380.0,127.0,1131.0
19,Fiat,PassengerCar,Grande Punto,ICE,0.0,0.0,8442.0,4694.0,4334.0,1372.0,372.0,103.0,0.0,0.0,0.0,0.0,19317.0
22,Fiat,PassengerCar,Linea,ICE,2593.0,2370.0,3015.0,1702.0,1091.0,487.0,115.0,100.0,0.0,0.0,0.0,0.0,11473.0
25,Fiat,SUV,Avventura,ICE,0.0,0.0,909.0,2170.0,1230.0,831.0,256.0,99.0,0.0,0.0,0.0,0.0,5495.0

In [30]:
for folders,subs,files in os.walk(os.getcwd()+'/annual_sales_by_model'):
    for file in files:
        print(file)

honda.html
fiat_jeep_citroen.html
vw.html
hundai_kia.html
tata.html
mahindra.html
suzuki.html
ford.html
renault_nissan.html
toyota.html
isuzu.html

In [31]:
brand = {}
flag=True

for folders,subs,files in os.walk(os.getcwd()+'/annual_sales_by_model'):
    for file in files:
        name = file.split('.')[0]
        brand.update({name:pd.read_html(os.getcwd()+'/annual_sales_by_model/'+file)[1]})
        
        brand[name].drop(columns=['Group','Country'],inplace=True)
        
        brand[name]['PowerTrain'].fillna('ICE',inplace=True)
        
        brand[name].drop(index=brand[name][brand[name]['PowerTrain'].str.contains('Total')].index,inplace=True)
        
        for value in brand[name][brand[name]['Maker/Brand'].str.contains(r'\W\d{0,}-\d{0,4}\W')][['Maker/Brand']].iterrows():
            brand[name].loc[value[0],'Maker/Brand'] = value[1].values[0].split()[0]
            
        brand[name].drop(index=brand[name][brand[name]['Model'].isna()].index,axis=0,inplace=True)
        
        for value in brand[name][brand[name]['Model'].str.contains(r'\W\D{0,}\W\d{0,}-\d{0,4}\W\W')][['Model']].iterrows():
            brand[name].loc[value[0],'Model'] = value[1].values[0].split()[0]
            
        years = brand[name].columns[4:]
        
        brand[name][years] = brand[name][years].replace('-',np.nan)
        brand[name].dropna(thresh=5,inplace=True)
                    
        brand[name].replace(np.nan,0,inplace=True)
        
        brand[name][years] = brand[name][years].astype('float')
        
        if len(brand[name][brand[name][brand[name].columns[:4]].duplicated()])>0:
            for items in brand[name].iterrows():
                if(list(items[1].values[:3])==list(brand[name][brand[name][brand[name].columns[:4]].duplicated()].values[0][:3])):
                    brand[name].loc[items[0],years]+=brand[name][brand[name][brand[name].columns[:4]].duplicated()][years].values[0]
                    break
            brand[name].drop(index=brand[name][brand[name][brand[name].columns[:4]].duplicated()].index,inplace=True)
            
        for indx,value in zip(range(0,len(brand[name])),brand[name]['Segment'].values):
            if re.search('SUV',value) or value=='MPV':
                brand[name].iloc[indx,1] = 'SUV'
                continue
            elif value in ['A','B','C','D','E','F']:
                brand[name].iloc[indx,1] = 'PassengerCar'
                continue
            elif value == 'Pickup Truck':
                brand[name].iloc[indx,1] = 'LightTruck'
                continue
                
        brand[name].drop(index=brand[name][brand[name]['Segment']=='Unclassified'].index,axis=0,inplace=True)
            brand[name]['Total'] = brand[name][years].sum(axis=1)
        
        brand[name].reset_index(drop=True,inplace=True)
        
        file_name=os.getcwd()+'/testing_cleaned/annual_sales_'+name+'.csv'
        brand[name].to_csv(file_name)
        
        if flag:
            master_data = brand[name]
            flag = False
            continue
        else:
            master_data = pd.concat([master_data,brand[name]],ignore_index=True,axis=0)
            
master_data.to_csv(os.getcwd()+'/testing_cleaned/annual_model_sales_master_data.csv')
master_data

,Maker/Brand,Segment,Model,PowerTrain,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Total
0,Honda,PassengerCar,Brio,ICE,0.0,0.0,13246.0,10618.0,7260.0,5412.0,2277.0,3.0,0.0,0.0,0.0,0.0,38816.0
1,Honda,PassengerCar,Brio Amaze,ICE,0.0,0.0,65505.0,63831.0,35388.0,28314.0,67563.0,67715.0,37484.0,39697.0,46528.0,41292.0,493317.0
2,Honda,PassengerCar,Fit (Jazz),ICE,0.0,0.0,0.0,29644.0,34902.0,29890.0,18370.0,9512.0,3254.0,7259.0,4167.0,0.0,136998.0
3,Honda,PassengerCar,Civic,ICE,1099.0,74.0,0.0,0.0,0.0,0.0,0.0,4928.0,1225.0,6.0,0.0,0.0,7332.0
4,Honda,PassengerCar,Honda City,ICE,32404.0,21530.0,77346.0,82922.0,57619.0,62573.0,42045.0,28696.0,21826.0,34133.0,38335.0,20216.0,519645.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Toyota,SUV,Vellfire,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,333.0,478.0,683.0,565.0,2089.0
179,Toyota,LightTruck,Hilux,ICE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,904.0,904.0
180,Isuzu,SUV,MU-7,ICE,0.0,0.0,176.0,385.0,224.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,785.0
181,Isuzu,SUV,MU-X,ICE,0.0,0.0,0.0,0.0,0.0,799.0,952.0,577.0,173.0,65.0,52.0,67.0,2685.0
182,Isuzu,LightTruck,D-Max,ICE,0.0,0.0,0.0,0.0,1241.0,3359.0,4934.0,4136.0,771.0,572.0,708.0,811.0,16532.0